channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter
  - numpy
  - matplotlib
  - scipy
  - awkward>=0.12.0,<1.0
  - uproot>=3.11.6
  - uproot-base>=3.11.6
  - uproot-methods>=0.7.0
  - cachetools
