[build-system]
requires = [
	"setuptools>=42.0",
	"wheel",
	"setuptools_scm[toml]>=4.1"
]
build-backend="setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pyBumpHunter/version.py"
local_scheme = "no-local-version"
